
lane :release do |options|
	tuist 

	app_subject = options[:subject]
	app_subject_plural = app_subject + "s"
	app_name = app_subject + "Finder"
	bundle_id = "com.dylanelliott." + app_name

	create_app_online(app_name: app_name, app_identifier: bundle_id)
	get_provisioning_profile(app_identifier: bundle_id, force: true)
    build_app(scheme: app_name)

    snapshot(devices:[
    	"iPhone 8",
    	"iPhone 11",
    ])

    upload_to_app_store(
    	submit_for_review: true,
    	subtitle: { "en-US": "Find your own way" },
    	primary_category: "Navigation",
    	price_tier: 1,
    	description: { "en-US": [
    		"#{app_name} is a location compass... for #{app_subject_plural.downcase}. It points you in the direction of the nearest #{app_subject.downcase}, so you can find your own way there. Simply open the app and follow your feet... to #{app_subject.downcase}.",
    		" ",
			"#{app_name} is a slimmed down version of Wayfinder. If you’d like to enter your own destinations, check out Wayfinder as well."
		].join("\n") },
		keywords: { "en-US":  [
			"directions",
			"compass",
			"location",
			"poi",
			"way",
			"find",
			"nearby",
			"walk",
			app_subject_plural.downcase
		] },
		support_url: { "en-US":  "http://dylanelliottiphone.blogspot.com.au" },
		marketing_url: { "en-US":  "http://dylanelliottiphone.blogspot.com.au" },
		copyright: "2020 Dylan Elliott",
		"app_review_information": {
			first_name: "Dylan",
			last_name: "Elliott",
			phone_number: "+61411834825",
			email_address: "dylan.elliott@gmail.com"
		},
		submission_information: {
			add_id_info_limits_tracking: true,
			add_id_info_serves_ads: false,
			add_id_info_tracks_action: true,
			add_id_info_tracks_install: true,
			add_id_info_uses_idfa: true,
			content_rights_has_rights: true,
			content_rights_contains_third_party_content: true,
			export_compliance_platform: 'ios',
			export_compliance_compliance_required: false,
			export_compliance_encryption_updated: false,
			export_compliance_app_type: nil,
			export_compliance_uses_encryption: false,
			export_compliance_is_exempt: false,
			export_compliance_contains_third_party_cryptography: false,
			export_compliance_contains_proprietary_cryptography: false,
			export_compliance_available_on_french_store: false
		},
		app_rating_config_path: "fastlane/metadata/age_rating_config.json",
		force: true
    )
  end

lane :tuist do
	sh("tuist generate -p .. --project-only")
end